427 hardcoded font in design system is hard to override
Nimble-Institute/nimble-design-system pull request #428
Opened 2024-08-02 08:55 UTC by keesvanopdorp

Inplemented the necessary changes

2024-08-02 20:48 UTC, Manoj201 requested changes
Every component font family is optional, so better to have default font family in the component level.

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleAutoComplete/NimbleAutoComplete.tsx
> -  fontFamily = 'Roboto,Helvetica,Arial,sans-serif',
fontFamily is optional prop, so don't remove this default value if prop is optional

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleAutoComplete/NimbleAutoComplete.tsx
> +  fontFamily,
fontFamily is optional prop, so don't remove this default value if prop is optional

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleBasicDataTable/NimbleBasicDataTable.tsx
> +  fontFamily,
please add default value for optional prop

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleButton/NimbleButton.tsx
> +  fontFamily,
as above comment please fix this

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleChip/NimbleChip.tsx
> +  fontFamily,
as above comment please fix this

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleDataGrid/NimbleDataGrid.tsx
> +  fontFamily,
as above comment please fix this

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleDataTable/NimbleDataTable.tsx
> +  fontFamily,
as above comment please fix this

2024-08-02 20:48 UTC, Manoj201 commented on src/components/nimbleFileUploader/NimbleFileUploader.tsx
> +  uploadButtonFontFamily,
as above comment please fix this

2024-08-03 09:33 UTC, keesvanopdorp commented
> if you are not of the same opinion as me and Max we need to discuss this in a meeting to find  a better solution for this problem because I'm of the opinion that this is not behavior you want in a component library. Furthermore in now need with every instance of a component you need to specify the font family if you don't use roboto

2024-08-03 09:38 UTC, keesvanopdorp commented
> if you are not of the same opinion as me and Max we need to discuss this in a meeting to find  a better solution for this problem for this because I'm still of the opinion that this is not behavior you want in a component library. Furthermore now you need every instance of a component you need to specify the font family if you don't use roboto or need to wrap every nimble component in a styled function and overwrite the font family

2024-08-07 12:08 UTC, closed without merging